<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Plan;

class PlansSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            // ─── Starter Monthly ──────────────────────────────────────────────
            [
                'id'                               => '5a262dba-a30b-481f-b69d-d0aae4f45eb1',
                'code'                             => 'starter',
                'plan_code'                        => 'starter',
                'name'                             => 'Jornafy Starter',
                'slug'                             => 'starter_monthly',
                'description'                      => 'Para pequenas equipas que precisam cumprir o registo de jornada com controlo simples.',
                'price_cents'                      => 1900,
                'monthly_price_cents'              => 1900,
                'yearly_price_cents'               => 18200,
                'extra_employee_price_cents'       => 250,
                'currency'                         => 'EUR',
                'billing_interval'                 => 'month',
                'trial_days'                       => 0,
                'included_employees'               => 5,
                'is_active'                        => true,
                'sort_order'                       => 10,
                'stripe_product_id'                => 'prod_UcEcAUXT6GGXIy',
                'stripe_price_id'                  => 'price_1Td09RHo1sUcOy0oG1HXbJuU',
                'stripe_extra_employee_product_id' => 'prod_UcEcfT6sGFyJop',
                'stripe_extra_employee_price_id'   => 'price_1Td09YHo1sUcOy0orf3Vo2DI',
                'features' => [
                    'time_tracking'    => true,
                    'journey_history'  => true,
                    'time_adjustments' => true,
                    'basic_export'     => true,
                    'simple_dashboard' => true,
                ],
                'quotas' => [
                    'max_employees'      => 5,
                    'included_employees' => 5,
                ],
            ],

            // ─── Starter Yearly ───────────────────────────────────────────────
            [
                'id'                               => 'c535363c-3b14-4446-abbd-1fca065786a0',
                'code'                             => 'starter',
                'plan_code'                        => 'starter',
                'name'                             => 'Jornafy Starter Anual',
                'slug'                             => 'starter_yearly',
                'description'                      => 'Para pequenas equipas que precisam cumprir o registo de jornada com controlo simples. Pagamento anual com 20% de desconto.',
                'price_cents'                      => 18200,
                'monthly_price_cents'              => 1900,
                'yearly_price_cents'               => 18200,
                'extra_employee_price_cents'       => 250,
                'currency'                         => 'EUR',
                'billing_interval'                 => 'year',
                'trial_days'                       => 0,
                'included_employees'               => 5,
                'is_active'                        => true,
                'sort_order'                       => 11,
                'stripe_product_id'                => 'prod_UcEcAUXT6GGXIy',
                'stripe_price_id'                  => 'price_1Td09SHo1sUcOy0oZui3r51x',
                'stripe_extra_employee_product_id' => 'prod_UcEcfT6sGFyJop',
                'stripe_extra_employee_price_id'   => 'price_1Td09YHo1sUcOy0orf3Vo2DI',
                'features' => [
                    'time_tracking'    => true,
                    'journey_history'  => true,
                    'time_adjustments' => true,
                    'basic_export'     => true,
                    'simple_dashboard' => true,
                ],
                'quotas' => [
                    'max_employees'      => 5,
                    'included_employees' => 5,
                ],
            ],

            // ─── Business Monthly ─────────────────────────────────────────────
            [
                'id'                               => 'd1f6e1ff-8afd-43db-bf07-99307942be1a',
                'code'                             => 'business',
                'plan_code'                        => 'business',
                'name'                             => 'Jornafy Business',
                'slug'                             => 'business_monthly',
                'description'                      => 'Para equipas em crescimento que precisam gerir jornada, férias, documentos e relatórios.',
                'price_cents'                      => 3900,
                'monthly_price_cents'              => 3900,
                'yearly_price_cents'               => 37400,
                'extra_employee_price_cents'       => 250,
                'currency'                         => 'EUR',
                'billing_interval'                 => 'month',
                'trial_days'                       => 0,
                'included_employees'               => 15,
                'is_active'                        => true,
                'sort_order'                       => 20,
                'stripe_product_id'                => 'prod_UcEcUaxfbSy3On',
                'stripe_price_id'                  => 'price_1Td09THo1sUcOy0oZzRBGUeJ',
                'stripe_extra_employee_product_id' => 'prod_UcEcfT6sGFyJop',
                'stripe_extra_employee_price_id'   => 'price_1Td09YHo1sUcOy0orf3Vo2DI',
                'features' => [
                    'time_tracking'    => true,
                    'journey_history'  => true,
                    'time_adjustments' => true,
                    'basic_export'     => true,
                    'simple_dashboard' => true,
                    'vacations'        => true,
                    'geolocation'      => true,
                    'documents'        => true,
                    'payroll'          => true,
                    'advanced_reports' => true,
                    'audit_logs'       => true,
                    'multi_admins'     => true,
                ],
                'quotas' => [
                    'max_employees'      => 15,
                    'included_employees' => 15,
                ],
            ],

            // ─── Business Yearly ──────────────────────────────────────────────
            [
                'id'                               => 'f627b4d8-5f15-481e-a6cd-f06eca41bf23',
                'code'                             => 'business',
                'plan_code'                        => 'business',
                'name'                             => 'Jornafy Business Anual',
                'slug'                             => 'business_yearly',
                'description'                      => 'Para equipas em crescimento que precisam gerir jornada, férias, documentos e relatórios. Pagamento anual com 20% de desconto.',
                'price_cents'                      => 37400,
                'monthly_price_cents'              => 3900,
                'yearly_price_cents'               => 37400,
                'extra_employee_price_cents'       => 250,
                'currency'                         => 'EUR',
                'billing_interval'                 => 'year',
                'trial_days'                       => 0,
                'included_employees'               => 15,
                'is_active'                        => true,
                'sort_order'                       => 21,
                'stripe_product_id'                => 'prod_UcEcUaxfbSy3On',
                'stripe_price_id'                  => 'price_1Td09VHo1sUcOy0ouqdPyP7T',
                'stripe_extra_employee_product_id' => 'prod_UcEcfT6sGFyJop',
                'stripe_extra_employee_price_id'   => 'price_1Td09YHo1sUcOy0orf3Vo2DI',
                'features' => [
                    'time_tracking'    => true,
                    'journey_history'  => true,
                    'time_adjustments' => true,
                    'basic_export'     => true,
                    'simple_dashboard' => true,
                    'vacations'        => true,
                    'geolocation'      => true,
                    'documents'        => true,
                    'payroll'          => true,
                    'advanced_reports' => true,
                    'audit_logs'       => true,
                    'multi_admins'     => true,
                ],
                'quotas' => [
                    'max_employees'      => 15,
                    'included_employees' => 15,
                ],
            ],

            // ─── Scale Monthly ────────────────────────────────────────────────
            [
                'id'                               => 'a73accb3-60f9-4658-b089-bc5431758895',
                'code'                             => 'scale',
                'plan_code'                        => 'scale',
                'name'                             => 'Jornafy Scale',
                'slug'                             => 'scale_monthly',
                'description'                      => 'Para operações maiores com áreas, permissões avançadas e suporte prioritário.',
                'price_cents'                      => 7900,
                'monthly_price_cents'              => 7900,
                'yearly_price_cents'               => 75800,
                'extra_employee_price_cents'       => 250,
                'currency'                         => 'EUR',
                'billing_interval'                 => 'month',
                'trial_days'                       => 0,
                'included_employees'               => 40,
                'is_active'                        => true,
                'sort_order'                       => 30,
                'stripe_product_id'                => 'prod_UcEcFr1qNZn075',
                'stripe_price_id'                  => 'price_1Td09WHo1sUcOy0o2VWXFTVt',
                'stripe_extra_employee_product_id' => 'prod_UcEcfT6sGFyJop',
                'stripe_extra_employee_price_id'   => 'price_1Td09YHo1sUcOy0orf3Vo2DI',
                'features' => [
                    'time_tracking'        => true,
                    'journey_history'      => true,
                    'time_adjustments'     => true,
                    'basic_export'         => true,
                    'simple_dashboard'     => true,
                    'vacations'            => true,
                    'geolocation'          => true,
                    'documents'            => true,
                    'payroll'              => true,
                    'advanced_reports'     => true,
                    'audit_logs'           => true,
                    'multi_admins'         => true,
                    'areas'                => true,
                    'advanced_permissions' => true,
                    'priority_support'     => true,
                ],
                'quotas' => [
                    'max_employees'      => 40,
                    'included_employees' => 40,
                ],
            ],

            // ─── Scale Yearly ─────────────────────────────────────────────────
            [
                'id'                               => 'cb52da2e-fc39-497e-a9ae-42dda0a36317',
                'code'                             => 'scale',
                'plan_code'                        => 'scale',
                'name'                             => 'Jornafy Scale Anual',
                'slug'                             => 'scale_yearly',
                'description'                      => 'Para operações maiores com áreas, permissões avançadas e suporte prioritário. Pagamento anual com 20% de desconto.',
                'price_cents'                      => 75800,
                'monthly_price_cents'              => 7900,
                'yearly_price_cents'               => 75800,
                'extra_employee_price_cents'       => 250,
                'currency'                         => 'EUR',
                'billing_interval'                 => 'year',
                'trial_days'                       => 0,
                'included_employees'               => 40,
                'is_active'                        => true,
                'sort_order'                       => 31,
                'stripe_product_id'                => 'prod_UcEcFr1qNZn075',
                'stripe_price_id'                  => 'price_1Td09XHo1sUcOy0o7EJbtsr9',
                'stripe_extra_employee_product_id' => 'prod_UcEcfT6sGFyJop',
                'stripe_extra_employee_price_id'   => 'price_1Td09YHo1sUcOy0orf3Vo2DI',
                'features' => [
                    'time_tracking'        => true,
                    'journey_history'      => true,
                    'time_adjustments'     => true,
                    'basic_export'         => true,
                    'simple_dashboard'     => true,
                    'vacations'            => true,
                    'geolocation'          => true,
                    'documents'            => true,
                    'payroll'              => true,
                    'advanced_reports'     => true,
                    'audit_logs'           => true,
                    'multi_admins'         => true,
                    'areas'                => true,
                    'advanced_permissions' => true,
                    'priority_support'     => true,
                ],
                'quotas' => [
                    'max_employees'      => 40,
                    'included_employees' => 40,
                ],
            ],
        ];

        foreach ($plans as $data) {
            Plan::withTrashed()->updateOrCreate(
                ['id' => $data['id']],
                array_merge($data, ['deleted_at' => null])
            );
        }
    }
}
