openapi: 3.0.0
info:
  title: "Ponto SaaS API"
  version: "1.0.0"
  description: "Documentação da API de Controle de Ponto"

servers:
  - url: https://api.meudominio.com/api
    description: Produção
  - url: http://localhost:8000/api
    description: Local

paths: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
