services:
  app:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    image: jornafy-api:latest
    container_name: laravel-app
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      LOG_CHANNEL: stderr
      RUN_COMPOSER_INSTALL: "false"
      RUN_MIGRATIONS: "true"
      RUN_OPTIMIZE: "true"
      WAIT_FOR_DB: "true"
    env_file:
      - .env
    networks:
      - laravel

  queue-worker:
    image: jornafy-api:latest
    container_name: laravel-queue
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      LOG_CHANNEL: stderr

      RUN_COMPOSER_INSTALL: "false"
      RUN_MIGRATIONS: "false"
      RUN_OPTIMIZE: "false"
      WAIT_FOR_DB: "true"
    env_file:
      - .env
    depends_on:
      - app
    command: ["php", "/var/www/artisan", "queue:work", "database", "--queue=default", "--sleep=1", "--tries=3", "--timeout=120"]
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
