server {
      listen 80;
      server_name _;

      root /var/www/public;
      index index.php;

      access_log /dev/stdout;
      error_log /dev/stderr;

      location / {
        try_files $uri $uri/ /index.php?$query_string;
      }

      location ~ \.php$ {

            if ($request_method = OPTIONS) {
                  add_header 'Access-Control-Allow-Origin' 'https://app.jornafy.com' always;
                  add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, PATCH, DELETE, OPTIONS' always;
                  add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin,X-Requested-With' always;
                  add_header 'Access-Control-Max-Age' 86400 always;
                  return 204;
            }

            add_header 'Access-Control-Allow-Origin' 'https://app.jornafy.com' always;
            add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type,Accept,Origin,X-Requested-With' always;

            try_files $uri =404;
            include fastcgi_params;

            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;
            fastcgi_param HTTPS on;

            fastcgi_pass app:9000;
            fastcgi_read_timeout 120;
      }

          client_max_body_size 100M;
}
