upload_max_filesize = 100M
post_max_size     = 100M
log_errors = On
error_log = /proc/self/fd/2
display_errors = Off
display_startup_errors = Off

; local dev: revalida arquivos a cada request
opcache.revalidate_freq = 0
opcache.validate_timestamps = 1