name: Deploy API (ECR -> EC2)

on:
    push:
        branches: ["main"]
    workflow_dispatch: {}

jobs:
    build-push-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            -   name: Login to Amazon ECR
                id: ecr-login
                uses: aws-actions/amazon-ecr-login@v2

            -   name: Build and push image to ECR
                env:
                    AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
                    AWS_REGION: ${{ secrets.AWS_REGION }}
                    ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
                    IMAGE_TAG: ${{ github.sha }}
                run: |
                    ECR_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
                    IMAGE="${ECR_URI}/${ECR_REPOSITORY}:${IMAGE_TAG}"
                    IMAGE_LATEST="${ECR_URI}/${ECR_REPOSITORY}:latest"

                    docker build \
                      --pull \
                      --no-cache \
                      --build-arg APP_BUILD_SHA="${IMAGE_TAG}" \
                      -f ./.docker/php/Dockerfile \
                      -t "$IMAGE" \
                      -t "$IMAGE_LATEST" \
                      .

                    docker push "$IMAGE"
                    docker push "$IMAGE_LATEST"


            - name: Deploy on EC2 via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      set -e
                      cd /opt/jornafy-api

                      # Login no ECR
                      aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
                        docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

                      # Pull e restart
                      docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
                      docker compose -f docker-compose.prod.yml up -d --pull always --force-recreate

                      # (Opcional) limpar imagens antigas
                      docker image prune -f
